### ISSUE TITLE
sayaka in xterm in sixel-compatible modified gnu screen (arakiken/screen)

### ISSUE THREAD

**Issue by animalsThink** [isaki68k/sayaka#15]
sayaka prints:
Terminal doesn't support control sequence, switch to --white
Terminal doesn't support sixel, switch to --no-image

I set $TERM to xterm-256color. But the same result.
Are there any way to make sayaka believe the terminal has  sixel support?

**Comment by isaki68k** [comment]
There is no way to do it.  And sayaka doesn't use $TERM to determine it.  If your terminal supports SIXEL, sayaka would detect it automatically.

`echo ^[[c` (`Control+V` `Control+[` `[` `c`) shows capability of your terminal.  If the terminal supports SIXEL, returned string contains `4`.

**Comment by animalsThink** [comment]
お返事ありがとうございます。本来screen側で対応すべきものなら残念ですが仕方ないですね。個人で使用するだけなのでterm.cppの114行と116行をコメントアウトして必ず真を返すようにしました。素敵なアプリを使えることに感謝しています。
環境:ubuntu jammy / openbox / tabbed + xterm + screent

**Comment by isaki68k** [comment]
ありがとうございます。時間が出来たらちょっと考えてみます。

**Comment by isaki68k** [comment]
ver 3.5.4 で --force-sixel オプションを用意しました。
