### ISSUE TITLE
pkg-config を README に必須コンポーネントとして書いて欲しい

### ISSUE THREAD

**Issue by moveccr** [isaki68k/sayaka#25]
素の wsl-ubuntu で ./configure すると pkg-config がないというエラーになりますが、
コンパイラも書いてあるぐらい親切なので、README に必須コンポーネントとして書いてもらえないでしょうか。

pkg-config のインストール自体は
`sudo apt install pkg-config`
で出来ました。

実行環境:
```
> uname -a
Linux yuzu 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by isaki68k** [comment]
追記しました。
