### ISSUE TITLE
3.7.0 以降で `--ciphers RSA` オプションが処理されていない?

### ISSUE THREAD

**Issue by tsutsui** [isaki68k/sayaka#26]
ような気がしたので C++なんもわからんと言いながら sayakaさん 3.5.x を参考に適当に書いてみたら
なんとなく動いているような？

```diff
--- src/HttpClient.cpp.orig	2024-03-03 04:31:18.000000000 +0000
+++ src/HttpClient.cpp
@@ -24,6 +24,7 @@
  * SUCH DAMAGE.
  */
 
+#include "sayaka.h"
 #include "HttpClient.h"
 #include "ChunkedInputStream.h"
 #if defined(USE_MBEDTLS)
@@ -91,6 +92,9 @@ HttpClient::Open(const std::string& uri_
 	ResultMsg.clear();
 	ResultCode = 0;
 	Ciphers.clear();
+	if (!opt_ciphers.empty()) {
+		SetCiphers(opt_ciphers);
+	}
 
 	tstream.reset();
 	chunk_stream.reset();
```
![misskey-ssl-sayaka-ciphers-1](https://github.com/isaki68k/sayaka/assets/3054480/30bf63c2-c63f-4636-a3df-0d9c4752f7e1)
![misskey-ssl-sayaka-ciphers-2](https://github.com/isaki68k/sayaka/assets/3054480/984e36ab-8e5a-4f52-be55-71ecde31a8e0)

**Comment by isaki68k** [comment]
ありがとうございます。修正しました。(まさかまだ書いてなかったとは…)
