### ISSUE TITLE
Build breaks due to -Werror

### ISSUE THREAD

**Issue by yurivict** [isaki68k/sayaka#35]
See the [log](https://pkg-status.freebsd.org/beefy22/data/140amd64-default/f550157a18a4/logs/errors/sayaka-3.5.1_2.log).

Version: 3.5.1
clang-18
FreeBSD 14.1

**Comment by isaki68k** [comment]
`-Wno-error=vla-cxx-extension` was added in `net-im/sayaka/Makefile` on FreeBSD ports.  It's not my issue.

In addition, sayaka 3.5.1 is too old and no longer available as Twitter client.
Would you contact your(FreeBSD's) port maintainer, please?

I've confirmed latest version is buildable on FreeBSD/amd64-14.0.
Anyway, thank you for reporting.
