### ISSUE TITLE
SIXEL の改行が何かおかしいらしい?

### ISSUE THREAD

**Issue by isaki68k** [isaki68k/sayaka#36]
https://social.mikutter.hachune.net/@tsutsuii/112950052461505088 (リンク先に画像)
> どうもこれが
> - sayaka さんが生成した sixel だと起きる （画像の /tmp/test.six）
> - img2sixel で生成した sixel では起きない （画像の /tmp/test2.six）
> という気がする（いずれにせよ mlterm libpng 版だけ）

https://social.mikutter.hachune.net/@tsutsuii/112950269001503020 (リンク先に画像)
> pkg_add で入れた gdk_pixbuf2 なし mlterm + sayaka さんでスクロール時のsixel端数部分にスクロール前の描画が残るのは再現するっぽい

https://social.mikutter.hachune.net/@tsutsuii/112950283643176274
> これはどちらかというと要件定義の問題で、sixelの右端や下端がフォントサイズの倍数でない場合に文字が一部隠れた場合に
・残った部分にある文字グリフを欠片を消去するのかしないのか
・残った部分にあるグリフを消去しない場合にその残った描画部分をスクロール時にどう扱うのか
というところを動作定義として決めるところからか

https://social.mikutter.hachune.net/@tsutsuii/112950289426288525
> ただ、sayakaさんが作ったsixel（~/.sayaka/cache 以下にあるやつ）だと起きるけど img2sixel で作った sixel だと起きない、というのもよくわからないけど、末端の処理が違ったりするのだろうか

**Comment by tsutsui** [comment]
https://misskey.io/notes/9ww4jilsskga00ie

> @tsutsuii@social.mikutter.hachune.net
> https://github.com/isaki68k/sayaka/blob/master/src/SixelConverter.h#L38 ここでNormal=1となっているのをNormal=0にすれば直ると思います。
> sayaka は、Normal=1となっていることにより、https://vt100.net/docs/vt3xx-gp/chapter14.html の PS2 を 1 にした sixel を吐き出しますが、1 は "Pixel positions specified as 0 remain at their current color" となっています。
> https://github.com/arakiken/mlterm/issues/81 で、PS2=1の場合、背景色での塗りつぶしを行わないよう修正したため、ご指摘の現象が起きているのだと思います。
> 挙動変更により、惑わせてしまってすみません。

https://misskey.io/notes/9ww4lje2mkf100lv

> @tsutsuii@social.mikutter.hachune.net
> PS2ではなくP2です。失礼いたしました。

ということだそうです

**Comment by isaki68k** [comment]
追加情報。

https://social.mikutter.hachune.net/@tsutsuii/112957949628836452
> いや、実はどちらでも関係ないっぽくて
https://github.com/arakiken/mlterm/commit/5123203273ace07c26e3247bee7e36bd247d5873
これが入っているかどうかです（gdk_pixbuf 版は pkgsrc のを使っていた）

> とりあえず sayakaさんを起動して垂れ流すほうが速い気もしますが、
> - sayakaさんで出力したsixelで
> - フォント幅8ドットの場合、横幅が 8の倍数-6 くらいの画像を用意して
> - スクロール後に画像の右端or下端の端数部分が来る位置に文字が存在する状態でスクロールさせる
と起きたと思います

**Comment by isaki68k** [comment]
https://misskey.io/notes/9x4hmz34eq0201oo
> あらきさん、これ(ここを書いたmoveccrさんによりますと)P2=1は多色刷りのため(先に色を出力したピクセルを次の色プレーンではそのビットを0にすることで残しておくため)に必要だと思っていたのですが、P2=0(ビットが0のピクセルは背景色で塗る)だと、最後に出力した色と背景色だけの2色の絵にならないでしょうか?

https://misskey.io/notes/9x4i1gtj8flm062i
> こちらでは再現しないので切り分けお願いします。mlterm 以外の SIXEL 端末(あるのか?)とか。こちらで常用してるのは mlterm (Features: implugin imagelib(builtin) utmp)で7x14フォントです (何が効いてるか分からないので何を出したらいいのか分からないですが)。

**Comment by isaki68k** [comment]
https://social.mikutter.hachune.net/@tsutsuii/112988982914395651
> 適当に NetBSD/amd64 10.0 マシンで作ってみました。
> 
> http://teokurebsd.org/tmp/mlterm-sixel-test/
>
> mlterm-sixel-test/pkgsrc-x11-mlterm-patched.tar.gz
pkgsrc-2024Q2 に対して
> https://github.com/arakiken/mlterm/commit/0af65caa1aa6e62b6c836299c4353dca16387b56
> https://github.com/arakiken/mlterm/commit/a4baddc173046ac0e1eaed0f1912fbb2578d769a
> https://github.com/arakiken/mlterm/commit/63bb60ee8b115bdca3e775dfce612e29a1e7ecfa
> https://github.com/arakiken/mlterm/commit/5123203273ace07c26e3247bee7e36bd247d5873
> https://github.com/arakiken/mlterm/commit/64552b10d450ce11026800d5b74430233f438b9b
> 相当のパッチを当てる pkgsrc/x11/mlterm 以下一式
> 
> gdk_pixbuf2/mlterm-3.9.3nb10.tgz
> 上記でデフォルトの PKG_OPTIONS で作ったパッケージ
> 
> libpng/mlterm-3.9.3nb10.tgz
> 上記で PKG_OPTIONS=fribidi m17nlib xft2 mlterm-fb で作ったパッケージ
> 
> test1.sixel
> test2.sixel
> 添付動画テスト用sixel
(動画)

> mlterm の HEAD 相当で無理やりパッケージ作っても同じ挙動は再現するようです

> xterm -ti 382 -fn 8x16 および -fn 7x14 では欠片が残ることはないようです
(動画)

**Comment by isaki68k** [comment]
あらきさんより
https://misskey.io/notes/9y5t8n9jtfvy0bbk
> VT330/VT340 Programmer Reference Manualに以下の記述があり、これに基づいて実装しています。なお、この記述と異なる点として、PhとPvが指定されていなくても、P2=0,2の場合は、背景色での塗りつぶしを行います。
> Ph and Pv do not limit the size of the image defined by the sixel data. However, Ph and Pv let you omit background sixel data from the image definition and still have a color background. They also provide a concise way for the application or terminal to encode the size of an image.
> NOTE: The VT300 uses Ph and Pv to erase the background when P2 is set to 0 or 2.

https://misskey.io/notes/9y5tbrojcs0g0d2l
> なお、「ビットが0のピクセルは背景色で塗る」とおっしゃっておられるのは、縦6ピクセルの色塗るたびにビットが0のピクセルも背景色で塗るという意味と理解しましたが、sixelが、ドットインパクトプリンタ用のシーケンスだった経緯を考えると、そのような動作は考えられない(物理的に不可能)かなと思います。

https://misskey.io/notes/9y5th7vnkcvr02av
> なお、P2=1のsixelを出力した際に画面がスクロールしてしまうと、画面にゴミが残ってしまう問題があったので、以下のcommitで修正しました(描画速度がかなり遅くなってしまいますが…)。今回の挙動変更でお手数をおかけしてしまい、申し訳ありませんでした。
> https://github.com/arakiken/mlterm/commit/92fa70f1da41fb2c8affd387e775d95f3e75ead4

**Comment by tsutsui** [comment]
こちらにも書いておきます

https://social.mikutter.hachune.net/@tsutsuii/113182777877260685
> 言い出しっぺ(?)なのでいろいろ読み直していたのですが
> - 最初の moveccr さんの疑問 https://misskey.io/notes/9x4hmz34eq0201oo について、P2=0 or 2 のときの "Pixel positions specified as 0 are set to the current background color." というのは、「今から描画しようとするsixelシーケンスのいずれのパレットでも0だったピクセルは background color になる」という解釈をすべきで、それに従った実装として「最初に background color で塗ってから sixel データを描画する」となっている、という回答
> - P2=1 のときの mlterm の動作として、sixel描画時に描画前の画像を残すべきだが、スクロールのときはスクロール前の位置にあったデータは background color で消去してからスクロールされたデータを書くべき（だが、それが消されていなかったので残ってしまった）
> という解釈かと思いました

つまり
* 普通にsixel描画するのであれば、 P2=2 (default) で問題ない
（「何も描画しないpixelについてもともと描画されていたデータを残したい」というときだけ P2=1 を使う）
* mlterm の https://github.com/arakiken/mlterm/commit/5123203273ace07c26e3247bee7e36bd247d5873 以降、 https://github.com/arakiken/mlterm/commit/92fa70f1da41fb2c8affd387e775d95f3e75ead4 より前では「P2=1のsixelを出力した際に画面がスクロールしてしまうと、画面にゴミが残ってしまう問題があった」が修正された（ので、issue発端のP2=1での描画の問題は見かけ上解決している）が、「sayakaさんが P2=1を使っていることが妥当か」ということとは別の問題

ということになると思います。

**Comment by isaki68k** [comment]
mlterm の問題で修正された模様。
