### ISSUE TITLE
Vala Build Error

### ISSUE THREAD

**Issue by saitoha** [isaki68k/sayaka#9]
Valaよくわからないんですが、

$ vala --version
Vala 0.26.1

$ make
srcfiles: sayaka.vala Diag.vala Dictionary.vala FileUtil.vala HttpClient.vala Json.vala OAuth.vala SixelConverter.vala StringUtil.vala Twitter.vala ParsedUri.vala System.OS.vala System.OS.native.c
checking sayaka.vala and objdir/sayaka.vapi .. no-update
checking Diag.vala and objdir/Diag.vapi .. no-update
checking Dictionary.vala and objdir/Dictionary.vapi .. no-update
checking FileUtil.vala and objdir/FileUtil.vapi .. no-update
checking HttpClient.vala and objdir/HttpClient.vapi .. need-to-update
valac --fast-vapi=objdir/HttpClient.vapi HttpClient.vala
checking Json.vala and objdir/Json.vapi .. no-update
checking OAuth.vala and objdir/OAuth.vapi .. no-update
checking SixelConverter.vala and objdir/SixelConverter.vapi .. no-update
checking StringUtil.vala and objdir/StringUtil.vapi .. no-update
checking Twitter.vala and objdir/Twitter.vapi .. no-update
checking ParsedUri.vala and objdir/ParsedUri.vapi .. no-update
checking System.OS.vala and objdir/System.OS.vapi .. no-update
checking sayaka.vala and objdir/sayaka.c .. no-update
checking /Users/hsaito/work/sayaka/vala/objdir/Diag.vapi and objdir/sayaka.c .. no-update
checking /Users/hsaito/work/sayaka/vala/objdir/Dictionary.vapi and objdir/sayaka.c .. no-update
checking /Users/hsaito/work/sayaka/vala/objdir/FileUtil.vapi and objdir/sayaka.c .. no-update
checking /Users/hsaito/work/sayaka/vala/objdir/HttpClient.vapi and objdir/sayaka.c .. need-to-update
valac --pkg posix --pkg gdk-pixbuf-2.0   -C -d objdir/ --deps=objdir/sayaka.dep --use-fast-vapi=objdir/Diag.vapi --use-fast-vapi=objdir/Dictionary.vapi --use-fast-vapi=objdir/FileUtil.vapi --use-fast-vapi=objdir/HttpClient.vapi --use-fast-vapi=objdir/Json.vapi --use-fast-vapi=objdir/OAuth.vapi --use-fast-vapi=objdir/SixelConverter.vapi --use-fast-vapi=objdir/StringUtil.vapi --use-fast-vapi=objdir/Twitter.vapi --use-fast-vapi=objdir/ParsedUri.vapi --use-fast-vapi=objdir/System.OS.vapi sayaka.vala
checking Diag.vala and objdir/Diag.c .. no-update
checking Dictionary.vala and objdir/Dictionary.c .. no-update
checking /Users/hsaito/work/sayaka/vala/objdir/Diag.vapi and objdir/Dictionary.c .. no-update
checking FileUtil.vala and objdir/FileUtil.c .. no-update
checking HttpClient.vala and objdir/HttpClient.c .. need-to-update
valac --pkg posix --pkg gdk-pixbuf-2.0   -C -d objdir/ --deps=objdir/HttpClient.dep --use-fast-vapi=objdir/sayaka.vapi --use-fast-vapi=objdir/Diag.vapi --use-fast-vapi=objdir/Dictionary.vapi --use-fast-vapi=objdir/FileUtil.vapi --use-fast-vapi=objdir/Json.vapi --use-fast-vapi=objdir/OAuth.vapi --use-fast-vapi=objdir/SixelConverter.vapi --use-fast-vapi=objdir/StringUtil.vapi --use-fast-vapi=objdir/Twitter.vapi --use-fast-vapi=objdir/ParsedUri.vapi --use-fast-vapi=objdir/System.OS.vapi HttpClient.vala
HttpClient.vala:183.15-183.39: error: The name `CONNECTION_CLOSED' does not exist in the context of `GLib.IOError'
				throw new IOError.CONNECTION_CLOSED("");
				          ^^^^^^^^^^^^^^^^^^^^^^^^^
HttpClient.vala:200.16-200.40: error: The name `CONNECTION_CLOSED' does not exist in the context of `GLib.IOError'
					throw new IOError.CONNECTION_CLOSED("");
					          ^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 0 warning(s)
make: *** [sayaka] Error 1

と言われてしまいました...

**Comment by isaki68k** [comment]
調べてみると、CONNECTION_CLOSED は glib2-2.44 で追加されたようですね…。
https://developer.gnome.org/gio/stable/gio-GIOError.html

glib2 のバージョンを上げてみてもらえますか。READMEにも追記しておきます。

**Comment by saitoha** [comment]
了解です。ためしてみます。

**Comment by saitoha** [comment]
やっと試せました。解決です。ありがとうございました。

**Comment by isaki68k** [comment]
了解です。お手数おかけしました。
